[package]
name = "cutaway-treesitter"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
cutaway-architecture.workspace = true
cutaway-inspection.workspace = true
thiserror.workspace = true
tree-sitter.workspace = true
tree-sitter-rust.workspace = true
